base:
  version: 1.25.5
  rollout: true
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause:
            duration: 2m
        - setWeight: 100
        - pause:
            duration: 4m
  progressDeadlineSeconds: 600
